var total = "124.0" 
console.log(typeof total);

window.alert(By continuing, you agree you are of age)

// When the user clicks on <div>, open the popup
function myFunction() {
  var popup = document.getElementById("myPopup");
  popup.classList.toggle("show");
}
/* Age Verification Pop Up */

overAge = function () {

  $('#age-verify').addClass('hidden');

}

underAge = function () {

  $('#age-verify').addClass('under');

}

goBack = function () {

    window.history.back();

}

